dataaugment: 'orion~choices(["cifar10", "imagenet", "svhn"])'
lr: 'orion~loguniform(1e-5,1.0)'
nepoch: '100'
patience: '10' 
batchsize: '8' 
filter1: '64'
ksize1: '3'
stride1: '1'
pool1: '2'
stridepool1: '2'
filter2: '128'
ksize2: '3'
stride2: '1'
pool2: '2'
stridepool2: '2'
filter3: '256'
ksize3: '3'
stride3: '1'
pool3: '2'
stridepool3: '2'
filter4: '512'
ksize4: '3'
stride4: '1'
pool4: '2'
stridepool4: '2'
filter5: '512'
ksize5: '3'
stride5: '1'
pool5: '2'
stridepool5: '2'
dense1: '4096'
dense2: '4096'
